### ISSUE TITLE
Would this work in React Native?

### ISSUE THREAD

**Issue by loganpowell** [JSxMachina/react-grid-system#50]
Just hoping that - since there's no CSS involved - this might work in React Native?

**Comment by mikehdt** [comment]
I believe the "no CSS" angle is a bit misleading. Sure, you don't _write_ any CSS when using this, but it certainly _uses_ CSS under the hood to do its layout. The end result _has_ to produce CSS, otherwise no layout could occur ;)

I'm only superficially familiar with React Native, but as far as I understand it transforms `flexbox` (not `float` or `inline-block`) and a few other properties into native view containers, depending on how the platform needs them (iOS vs Android etc). Looking at https://github.com/JSxMachina/react-grid-system/blob/master/src/grid/Col/style.js -- it seems to be using `flexbox`, which is an encouraging sign. However, I'm not sure what form React Native needs the CSS to be in, in order to transform it.

If it doesn't work as-is, and it isn't easy to modify things to suit, it may be better to pursue a solution for React Native that is tuned to its and your particular layout needs :)

**Comment by loganpowell** [comment]
I'll give it a go. Thank you!

**Comment by gerbenmeyer** [comment]
@mikehdt one could argue though that inline styles aren't actually cascading styles :)

**Comment by mikehdt** [comment]
Yet with inline styles, they're super rigid and have higher precedence -- so if you have a sane setup for dealing with class names etc., such as css-modules, it can sometimes end up being more trouble than it's worth ;)
